### ISSUE TITLE
Error:Module 'com.github.drawers:SpinnerDatePicker:0.0.4' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by felipecastilhos** [drawers/SpinnerDatePicker#1]
I'm trying to include the lib to my project, but I got this error:

    Error:Module 'com.github.drawers:SpinnerDatePicker:0.0.4' depends on one or more Android Libraries but is a jar

and this is my gradle file :
    `repositories {
    maven { url "https://clojars.org/repo/" }
    maven { url "https://jitpack.io" }
    maven { url 'https://maven.fabric.io/public' }
    mavenCentral()
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile('com.github.afollestad.material-dialogs:core:0.8.5.8@aar') {
        transitive = true
    }
    //----- Dagger
    //Required by Dagger2
    compile('com.crashlytics.sdk.android:crashlytics:2.6.5@aar') {
        transitive = true;
    }
    compile files('libs/RegoPrinLib.jar')
    compile files('libs/PrinterLib.jar')
    compile files('libs/PRT_SDK.jar')
    compile 'com.google.android.gms:play-services:11.0.2'
    compile 'com.google.dagger:dagger:2.0.2'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:support-v13:24.2.0'
    compile 'com.android.support:design:25.3.1'
    compile 'com.google.android:flexbox:0.2.5'
    compile 'com.rengwuxian.materialedittext:library:2.1.4'
    compile 'com.github.douglasjunior.BetterSpinner:library-material:bugfix-1.1.0-2'
    compile 'com.wdullaer:materialdatetimepicker:2.3.0'
    compile 'com.prolificinteractive:material-calendarview:1.3.0'
    compile 'com.journeyapps:zxing-android-embedded:3.2.0@aar'
    compile 'com.jakewharton:butterknife:8.4.0'
    compile 'com.google.zxing:core:3.2.1'
    compile 'com.squareup.retrofit2:retrofit:2.0.1'
    compile 'com.squareup.retrofit2:converter-gson:2.0.1'
    compile 'com.squareup.okhttp3:logging-interceptor:3.2.0'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'net.danlew:android.joda:2.9.4.1'
    compile 'org.honorato.multistatetogglebutton:multistatetogglebutton:0.2.2'
    compile 'com.github.douglasjunior:android-simple-tooltip:0.2.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'uk.co.chrisjenx:calligraphy:2.2.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.roughike:bottom-bar:2.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.github.drawers:SpinnerDatePicker:0.0.4'
    testCompile 'junit:junit:4.12'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
    apt 'com.google.dagger:dagger-compiler:2.0.2'
    provided 'javax.annotation:jsr250-api:1.0'
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.2'
    provided 'org.glassfish:javax.annotation:10.0-b28'
}`

**Comment by drawers** [comment]
Thanks for reporting this error I will look into it. In the meantime can you try `com.github.drawers.SpinnerDatePicker:0.0.5`?

**Comment by drawers** [comment]
Uhhh - I just checked the syntax and it should be: 

`compile 'com.github.drawers:SpinnerDatePickerLib:0.0.5'`

Sorry about that. The repo also contains a sample app with test cases and this is what was causing the problem. I'll update the README.MD

**Comment by drawers** [comment]
Looking into this now

**Comment by drawers** [comment]
Thanks for reporting the issue. I'm still learning to use jitpack and it seems I haven't configured it properly. For now you can use:

`compile 'com.github.drawers:SpinnerDatePicker:0.0.6@aar'` 

which is a bit messy but will work (have checked in sample project). In the future I will try and fix it. Good luck!

**Comment by drawers** [comment]
Fixed in #2
