### ISSUE TITLE
Title not updating while changing the date

### ISSUE THREAD

**Issue by palto-blubek** [drawers/SpinnerDatePicker#12]
I'm trying out this lib, and it seems to work well, except while I'm adjusting the date, it doesn't update the title (showing the date that's being picked).

I've checked, and this title is updated on the stock Kitkat date picker, as well as on the birth date picker of the Android contacts app.

Ideas?

**Comment by drawers** [comment]
Thanks for pointing this out. Looks like that bug has been there a while. It's a one line fix - I'll get it out soon
