### ISSUE TITLE
Dont change month on dayOfMonth scroll

### ISSUE THREAD

**Issue by smholsen** [drawers/SpinnerDatePicker#15]
Hi!
Great picker, thank you!

I was wondering if it is possible to disable the functionality of it changing the month if I scroll past the min and max dayOfMonth?

Say if I set the timer to 1.st of april, and then scroll the dayOfMonth backwards to 31, it would cause a change in the month scroller.

Is it possible to disable this functionality?

Best regards

**Comment by drawers** [comment]
Hi, can you please try one of the earlier versions of this library? 

https://jitpack.io/#drawers/SpinnerDatePicker

 I think version 0.0.8 might have the behaviour you want.
