### ISSUE TITLE
Unable to change divider color and cancel/ok button text colors on Android 5.0

### ISSUE THREAD

**Issue by JoshuaRodriguez** [drawers/SpinnerDatePicker#19]
I followed the same exact example as shown on the main page. The colors change on Android 6.0+, but when I check on a device with Android 5.0 the only things that changed was the text color for the month, day, and year. 

is it possible I might be missing something else?

Below is an example of my XML and code:

    <style name="JourneyDatePickerTheme">
        <item name="android:textSize">22dp</item>
        <item name="android:textColorPrimary">@color/charcoal</item>
        <item name="android:colorControlNormal" tools:targetApi="lollipop">@color/purplish_pink</item>
    </style>

`datePickerDialog
                    .context(it)
                    .spinnerTheme(R.style.JourneyDatePickerTheme)
                    .defaultDate(year, month, day)
                    .build()
                    .show()`

What I am getting on API 21:

![screen shot 2018-03-04 at 1 21 12 pm](https://user-images.githubusercontent.com/11702924/36948884-14cfaa54-1faf-11e8-8ab6-7c82d44c9482.png)

How it's supposed to look:

![screenshot_20180304-132256](https://user-images.githubusercontent.com/11702924/36948957-0fd8b62a-1fb0-11e8-90b3-d43762d4ac49.png)

**Comment by drawers** [comment]
Is this on all API 21 phones or just one or two?

**Comment by drawers** [comment]
I'll have a look but this might have to be worked around using reflection which I was hoping to avoid

**Comment by JoshuaRodriguez** [comment]
@drawers Sorry for replying so late, got really busy since I last posted this. To be frank I have not been testing on an actual device with Android 5.0 I have however used multiple emulators and the issue is easily reproduced.

**Comment by drawers** [comment]
The proposed solution is to have an extra field on the builder `fallbackDividerColor` as a fallback for cases where the style inflation fails. This would be set using reflection on API < 22 using the technique [in this StackOverflow question] (https://stackoverflow.com/questions/24233556/changing-numberpicker-divider-color)

**Comment by TalbotGooday** [comment]
The only way I've found to change buttons color is call after `dialog.show()` something like this
` dialog.getButton(DialogInterface.BUTTON_POSITIVE).setTextColor(getResources().getColor(R.color.colorStart));
                dialog.getButton(DialogInterface.BUTTON_NEGATIVE).setTextColor(getResources().getColor(R.color.colorStart));`

**Comment by drawers** [comment]
Another solution would be to try using the library Paris even though this is an external dependency:

https://github.com/airbnb/paris

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
