### ISSUE TITLE
Disable fields

### ISSUE THREAD

**Issue by vincentvanzyl** [drawers/SpinnerDatePicker#20]
Hi. This is a great library. It would be great if there could be a way to disable the day selection so that I have the option of only having a month / year selection. Or at least a way to get the DatePicker so that I can hide the view myself if I do not want it

**Comment by drawers** [comment]
Hi! thanks for the suggestion. This is the subject of pull request #17 which is currently being reviewed

**Comment by danielpassos** [comment]
I was about to open an issue with the same request. I hope it get merge soon

**Comment by drawers** [comment]
Can you please try version `1.0.6` to see if this satisfies your use cases?
