### ISSUE TITLE
Optionally customizable dialog title

### ISSUE THREAD

**Issue by bartonstanley** [drawers/SpinnerDatePicker#23]
The title on the date picker dialog is simply the date that is being picked.  It would be good if the dialog title could optionally match the label that is associated date picker.  For example, if the label associated with the date picker is "Date of Birth" then the title of the dialog would also be "Date of Birth".

**Comment by ovitrif** [comment]
Can be done easily :)

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
