### ISSUE TITLE
Theme for dialog display in format Day - Month - Year instead of Month - Day - Year. 

### ISSUE THREAD

**Issue by socheat-leang** [drawers/SpinnerDatePicker#24]
I saw on your summary  with **The old "spinner" style DatePicker for newer devices.**, it alert dialog with format day - month - year, but when I used, it display in format month-day-year. in this case, problem with device or what ?.or I missed spinnerTheme property. your doc should be clear about this.
thank .

**Comment by drawers** [comment]
Hi! Thanks for reporting the issue. The day/month/year order is determined by the locale of the device. So if your device has the locale set to US it will be month/day/year. If your device has locale set to UK it will be day/month/year. I'll try and update the docs some time.

**Comment by socheat-leang** [comment]
Thank you for reply. :D
