### ISSUE TITLE
There is a problem when you pick a date, it starts Month counting at 0, then it goes up to 11 

### ISSUE THREAD

**Issue by eliolako** [drawers/SpinnerDatePicker#25]
Says :
January 0; 
December 11;

**Comment by drawers** [comment]
Hi! I know it's not ideal but months are indexed from 0 in Java if this is what you are referring to here. If I broke the convention here I think it would be a little confusing

**Comment by ovitrif** [comment]
@cod-e-rection 
The code should work as code, starting from 0. Clients should parse this accordingly. It was the case with all other date libs I used, I had to manually increment/ decrement before accessing the lib, and I'm fine with it.

That doesnt mean the lib cant provide convenience methods
