### ISSUE TITLE
UX Issue while providing max date

### ISSUE THREAD

**Issue by jayshildave** [drawers/SpinnerDatePicker#26]
If current date is provided as max date. It results in below UX behavior under below steps results in an additional date getting as shown below.

Steps to reproduce:
- Set max date as today's date April 6th, 2018
- It doesn't show anything in third row as expected, since user cannot select a date in future
- User selects 2017 year and is shown to select date and month ahead
- User selects 2018 back without changing results in 01 being displayed after the current day 06 in the day number picker. Image attached for reference
![device-2018-04-06-152426](https://user-images.githubusercontent.com/715091/38442754-55065a06-39b7-11e8-96f2-4c9bca6d2653.png)

**Comment by drawers** [comment]
Thanks for reporting the bug. The repro' steps are very good so kudos to you! 

However, this may not be as serious as it seems since that behaviour comes directly from the AOSP DatePicker. A follow-up investigation would check if the AOSP DatePicker (pre-Lollipop) behaves in the same way.

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
