### ISSUE TITLE
A lot of unnecessary code

### ISSUE THREAD

**Issue by ovitrif** [drawers/SpinnerDatePicker#27]
Hi!

I noticed there is a lot of unused code in the repo, is there a purpose for it?
I think removing it would increase the maintainability of the project.

**Comment by drawers** [comment]
Hi! You are welcome to submit a pull request if you can remove the unused code safely and keep the text fixtures in place (the example project). I am working 50 + hour weeks so I don't have much time to maintain the project right now.

**Comment by ovitrif** [comment]
Sure, I would be happy to submit A pull request :)

P.S. I really like the idea of the library, it's something that most product people notice, the material design date picker is of a poor user experience 👍

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
