### ISSUE TITLE
Unable to add dependency 

### ISSUE THREAD

**Issue by wildfiregt** [drawers/SpinnerDatePicker#28]
Adding  compile 'com.github.drawers:SpinnerDatePicker:1.0.6' to project gradle build file returns 
 Failed to resolve: com.github.drawers:SpinnerDatePicker:1.0.6

Something is wrong ,the link maybe ?

**Comment by drawers** [comment]
Hi!

Did you add:

> allprojects {
>     repositories {
>         maven { url "https://jitpack.io" }
> 	   }
> }

Like in the README.md?

**Comment by wildfiregt** [comment]
My bad I thought I did 
Fixed now thanks
