### ISSUE TITLE
Feature Request: Maximum Date

### ISSUE THREAD

**Issue by ed-george** [drawers/SpinnerDatePicker#3]
Fantastic library, but if possible could you look into the possibility of adding a "maximum date" field to the builder.

What I mean by this is, after specifying a maximum date, the picker should not be able to pick a date greater than the given maximum. By default, this could be the current day or extended to any given date.

Sadly I cannot make a PR at present, so I hope this is something you can see value in and implement in future.

**Comment by drawers** [comment]
Yes, that is a reasonable request. I'll see if I have time this weekend to work on max/min date.

**Comment by drawers** [comment]
Completed in pull request #8
