### ISSUE TITLE
Localization not working correctly.

### ISSUE THREAD

**Issue by Pesof** [drawers/SpinnerDatePicker#31]
Localization on the default date pickers works flawlessly by picking the app's language, however. this one is using the device's language localization.

Any Idea how to fix this?

**Comment by drawers** [comment]
Hi! What do you mean? The library has the same behaviour as the default Android Datepicker with respect to localization I think (since it is only slightly modified from the AOSP picker). So if you change the language on your device this will be reflected in the DatePicker

**Comment by Pesof** [comment]
Maybe I couldn't explain myself clear, The language of this datepicker is changing when the devices languages change only not when I change the app's locale language.
But the default Android DatePicker is changing the language depending on my app's language, which I couldn't achieve using this library.

**Comment by drawers** [comment]
If I understand correctly, you shouldn't offer the user a place to change the language within the app and you shouldn't be updating the locale for the JVM in which your app runs manually.  The app should be adapt to the system/device locale - nothing more nothing less.
