### ISSUE TITLE
minor : showDay to showDaySpinner

### ISSUE THREAD

**Issue by monsterbrain** [drawers/SpinnerDatePicker#32]
In the homepage example please replace 
.showDay(true)
to
.showDaySpinner(true)

**Comment by drawers** [comment]
Hi! Thanks for telling me about the bug. I like to give a chance to programmers who are new to open source and GitHub to make pull requests with this project. Then you get a chance to have the contribution appear on your GitHub graph etc.

You are welcome to make a pull request to make the change yourself. The file you need to modify is README.md. Let me know if you need any help.

**Comment by monsterbrain** [comment]
I really appreciate your comment and providing me with this opportunity. I haven't done any pull request. Perhaps this might be a good start I guess. I'll let you know if I got into trouble though ... :)

**Comment by drawers** [comment]
Fixed in #33
