### ISSUE TITLE
android:supportsRtl

### ISSUE THREAD

**Issue by toyamah** [drawers/SpinnerDatePicker#35]
I’d like to propose that `android:supportsRtl` is removed from AndroidManifest.xml of this project.

The reason is,  when we use it to an app that the AndroidManifest defines `android:supportsRtl=false` attribute, we have to add `tools:replace` attribute.

**Comment by drawers** [comment]
Hi! Good idea! We would like to encourage you to make the pull request for this yourself. If you make the pull request, I will approve it promptly. Let me know if you need any help!

**Comment by drawers** [comment]
Fixed in 2.0.1
