### ISSUE TITLE
Keyboard is not dismissed if editing a month name and changing month afterwords

### ISSUE THREAD

**Issue by frogman544** [drawers/SpinnerDatePicker#36]
Keyboard is not dismissed if editing a month name, and with the keyboard open you swipe to other month. After swiping to the other month the keyboard is still visible but the cursor is gone, and the IME key button is set to "enter" and if you press it, nothing happens.
You only have the option to dismiss the keyboard by pressing back (close keyboard) button
Can you please dismiss the keyboard in the event of loosing focus from the current month that is being edited? Thank you!

**Comment by drawers** [comment]
Thanks for reporting - and you are welcome to submit a patch if you would like to do so! Do you know if this same problem affects the standard Android date picker (you can see this through the AOSP contacts app when you edit the date of birth for a contact)?

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
