### ISSUE TITLE
Support AndroidX MaterialTheme

### ISSUE THREAD

**Issue by vanyasem** [drawers/SpinnerDatePicker#37]
Currently the buttons are messed up when using a new MaterialTheme
![2018-11-23-020736_652x527_scrot](https://user-images.githubusercontent.com/13350458/48923991-8eb49480-eec4-11e8-8a14-8b2b24444165.png)

**Comment by vanyasem** [comment]
If you remove the "default theme" parameter, the buttons will be shown correctly

![2018-11-23-053629_655x509_scrot](https://user-images.githubusercontent.com/13350458/48926748-c120ba80-eee1-11e8-9286-c981d90c0b9c.png)

**Comment by sgaikar1** [comment]
use .Bridge in front of your parent theme,
 ex. **Theme.MaterialComponents.Light.NoActionBar.Bridge** i am using it in my project

**Comment by kutukoff** [comment]
Same problem

**Comment by ghost** [comment]
Same

**Comment by Sloy** [comment]
I forked the project to fix this issue: https://github.com/Sloy/SpinnerDatePicker
The artifact is published in Jitpack too, so replacing the original dependency with `com.github.Sloy:SpinnerDatePicker:1.0.6-androidx` will make it work.

I also sent a Pull Request, in case the author wants to merge it: https://github.com/drawers/SpinnerDatePicker/pull/42
