### ISSUE TITLE
How to set current date?

### ISSUE THREAD

**Issue by abby1602** [drawers/SpinnerDatePicker#49]

**Comment by sadeghibehzad** [comment]
@abby1602 Hi there
for current date just as document says 
use .defaultDate(YEAR,MONTH,DAY)
Like code below
`SpinnerDatePickerDialogBuilder picker = new SpinnerDatePickerDialogBuilder();
                    picker.context(getActivity())
                            .spinnerTheme(R.style.NumberPickerStyle)
                            .showTitle(true)
                            .showDaySpinner(true)
                            .maxDate(Calendar.getInstance().get(Calendar.YEAR) + 1, 12, 31)
                            .minDate(Calendar.getInstance().get(Calendar.YEAR) - 1, 0, 1);
                        picker.defaultDate(Calendar.getInstance().get(Calendar.YEAR),  Calendar.getInstance().get(Calendar.MONTH),Calendar.getInstance().get(Calendar.DAY_OF_MONTH));
                    picker.build().show();`

Or 

`new SpinnerDatePickerDialogBuilder().context(getActivity())
.spinnerTheme(R.style.NumberPickerStyle)
 .showTitle(true)
.showDaySpinner(true)
.maxDate(Calendar.getInstance().get(Calendar.YEAR) + 1, 12, 31)
.minDate(Calendar.getInstance().get(Calendar.YEAR) - 1, 0, 1)
.defaultDate(Calendar.getInstance().get(Calendar.YEAR),  Calendar.getInstance().get(Calendar.MONTH),Calendar.getInstance().get(Calendar.DAY_OF_MONTH));
.build()
.show();`

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
