### ISSUE TITLE
License info not available from POM

### ISSUE THREAD

**Issue by estrnod** [drawers/SpinnerDatePicker#50]
I use a license list generator library to create the list of dependencies I have in my app, with their licenses.  There are a couple, including yours, which do not show a connection to their license.  

I have opened an issue on their side (jk1/Gradle-License-Report#154), to hopefully allow for manual entry of the info in case it just can't be picked up from a dependency pom, but it'd be helpful for many users if you could make it available at your end.

I don't see a POM in your project, but since the help includes linking to it via maven repository, I'm opening this request in the hopes that with a small change, license attribution can happen automatically in this (and probably other) licenses report.

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
