### ISSUE TITLE
onCancel callback not working

### ISSUE THREAD

**Issue by Sanjeevs1995** [drawers/SpinnerDatePicker#55]
Hi I am not able to get cancel callback while using spinner date picker.

Below is my code for initializing.

```java
        new SpinnerDatePickerDialogBuilder()
                .context(JoinNowActivity.this)
                .callback(JoinNowActivity.this)
                .spinnerTheme(R.style.NumberPickerStyle)
                .showTitle(true)
                .showDaySpinner(true)
                .defaultDate(currentYear, currentMonth, currentDay)
                .maxDate(currentYear, currentMonth, currentDay)
                .minDate(1900, 0, 1)
                .build()
                .show();
```

i am able to set date but not able to get the cancel action/callback from the function.

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
