### ISSUE TITLE
Date and time not display

### ISSUE THREAD

**Issue by jaydeep2158** [drawers/SpinnerDatePicker#56]
Hello sir,
  I have to implement your library but some device date and time, not displayed.
  Please see this image : https://imgur.com/ztzG7K4
Thanks 
Jaydeep Dhamecha

**Comment by drawers** [comment]
Sorry, I cannot support this project any more. You are welcome to fork it and continue to do the work yourself (because it is set up with Jetpack you will get the CI for free)
